name: Security audit

on:
  workflow_call:
  push:
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
